### ISSUE TITLE
online process: video analyser hangs in spinning circle waiting for score result

### ISSUE THREAD

**Issue by mmagaldi-eng** [fandangOrg/fandango#102]
@pstalidis reported an issue to manage multiple requests on the video service side

**Comment by pstalidis** [comment]
The actual problem is that the backend service blocks other requests while performing the analysis.

This is an unexpected behaviour which has the effect of not responding to the front end with the progress of the analysis, therefore the user experiences an unresponsive system.

I am testing various solutions and will report back

**Comment by pstalidis** [comment]
A note for future reference: using --threads flag changes sync worker class to threaded which is not correctly monkey patched.
Also, default number of workers is 1 so -w flag is also redundant if only 1 worker is needed.

The issue has been solved.
