### ISSUE TITLE
increase "topic" tiles quality on SIREN dashboards

### ISSUE THREAD

**Issue by mmagaldi-eng** [fandangOrg/fandango#122]
@vittorianovancini, @jdgryse, @dcabo, please pass to @neilpbyrne an updated list of "stop words" (in ES, IT, NE).

**Comment by vittorianovancini** [comment]
[stopwords.txt](https://github.com/fandangOrg/fandango/files/6155206/stopwords.txt)
This is a list of stop-words, revised and updated with VRT for the Dutch. English stop-words are also included, but they're already pretty good in the system.  Spanish and Italian seem to work fine with this list, but I'd like to see them at work as soon as possible, in order to judge the enhancement results...

**Comment by mmagaldi-eng** [comment]
@neilpbyrne, did you update the stopwords list?

**Comment by neilpbyrne** [comment]
@mmagaldi-eng I did indeed. Let me know if it has improved the results.

**Comment by mmagaldi-eng** [comment]
> @mmagaldi-eng I did indeed. Let me know if it has improved the results.

@jdgryse @vittorianovancini
