### ISSUE TITLE
Duplicates on analyzed_media topic

### ISSUE THREAD

**Issue by federicovagnoni** [fandangOrg/fandango#41]
We started the crawler again this morning and it seems that certh_media_service is producing duplicates.

Reading from analyzed_media topic in kafka, we can see an example:
![immagine](https://user-images.githubusercontent.com/4192579/61786517-267cd080-ae0e-11e9-84a3-8a3c176715b9.png)

![immagine](https://user-images.githubusercontent.com/4192579/61786677-7fe4ff80-ae0e-11e9-81fd-bb0340f5d7bd.png)

**Comment by pstalidis** [comment]
Did you also restart the media analysis service, or the preprocessing service?

Both services use the kafka-python library to read the kafka topics which has a known bug.
The last processed article before stopping the service is analyzed again as the first article when the service starts. This has to do with starting **from** and not **after** the last committed message.

**Comment by federicovagnoni** [comment]
I only started the crawler. All the service were already online. 
But the duplicates are generated during the execution. It seems that they are not so frequent, anyway.

**Comment by pstalidis** [comment]
I added a live tail an hour ago and I haven't seen any duplicates.
Let's monitor this a bit longer and look at it again next week.

**Comment by federicovagnoni** [comment]
I found two occurences in the last 10 minutes:
2 | dd8754ea5ed8093a87f3fd044dc2f9bf770a0956448c5f2effae838f8f84d81b67c6d880587a89e00641fc0d20851d9f561c792461280ff2ca1a234dffa92ab6

The first number counts the occurences in the topic. I'm pretty sure they are subsequent like I showed you before.

![immagine](https://user-images.githubusercontent.com/4192579/61797222-3e148300-ae27-11e9-97e8-b44b6da827dd.png)

**Comment by pstalidis** [comment]
I just checked the input_raw and input_preprocessed queue. The exact same duplicates are also in the input_preprocessed 
![input_preprocessed](https://user-images.githubusercontent.com/24522654/61797994-335eeb80-ae31-11e9-902c-c7394ee65035.png)
but **not** in the input_raw topic.
![input_raw](https://user-images.githubusercontent.com/24522654/61797980-2d690a80-ae31-11e9-9535-bdd03c5f2348.png)

So the problem seems to originate in the preprocessing service. 
@dmgutierrez I am assigning this to you

**Comment by pstalidis** [comment]
analyzed media processes duplicates originating earlier in the queue. (added issue #63 )
