### ISSUE TITLE
[First Pilot] Execution scheduling with users

### ISSUE THREAD

**Issue by jefersonzanim** [fandangOrg/fandango#57]
Plan the dates for the manual and the FANDANGO data collection to be carried out.

**Comment by jefersonzanim** [comment]
@dcabo @vittorianovancini @ilkelemmelijn can you, please, confirm what would be the earliest date we could discuss this? I know @dcabo will be on holidays for 2 weeks, but we can try to pencil it in right after that.

Thanks!

**Comment by vittorianovancini** [comment]
?I'm available the whole month (but not on Ferragosto), just choose the date...


________________________________
Da: jefersonzanim <notifications@github.com>
Inviato: mercoledì 31 luglio 2019 17:33
A: fandangOrg/fandango
Cc: Vancini Vittoriano; Mention
Oggetto: Re: [fandangOrg/fandango] [First Pilot] Execution scheduling with users (#57)


@dcabo<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fdcabo&e=8a11e804&h=83510602&f=n&p=y> @vittorianovancini<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fvittorianovancini&e=8a11e804&h=bc547a3d&f=n&p=y> @ilkelemmelijn<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Filkelemmelijn&e=8a11e804&h=f0ed3674&f=n&p=y> can you, please, confirm what would be the earliest date we could discuss this? I know @dcabo<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fdcabo&e=8a11e804&h=83510602&f=n&p=y> will be on holidays for 2 weeks, but we can try to pencil it in right after that.

Thanks!

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2FfandangOrg%2Ffandango%2Fissues%2F57%3Femail_source%3Dnotifications%26email_token%3DAI7AQPZUV6PAWXNDDW6H2QTQCGWC5A5CNFSM4IIH6KCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3HUUCY%23issuecomment-516901387&e=8a11e804&h=21b2d7b1&f=n&p=y>, or mute the thread<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAI7AQP46BEZKF5OZHUPDAJTQCGWC5ANCNFSM4IIH6KCA&e=8a11e804&h=f1f844ba&f=n&p=y>.

________________________________

Il contenuto di questa e-mail è rivolto unicamente alle persone alle quali è indirizzato; le relative informazioni sono da considerarsi strettamente riservate e tutelate ai sensi del Regolamento UE 2016/679 (GDPR) per la Protezione dei Dati Personali, nonché del D. Lgs. n. 196/2003 e successive modifiche. Sono vietati la riproduzione, la diffusione e l'uso di questa e-mail in mancanza di autorizzazione del destinatario. In caso di ricezione della presente e-mail per errore, si prega di non diffonderla, di informare immediatamente il mittente e di eliminarne ogni copia. Le opinioni espresse in questa e-mail appartengono esclusivamente al mittente e potrebbero non riflettere necessariamente quelle dell'Agenzia ANSA.

The content of this e-mail is only addressed to the people to whom it is addressed; the relevant information has to be considered as confidential and protected under the Regulation EU 2016/679 (GDPR), General Data Protection Regulation, as well as the Legislative Decree 196/2003 and subsequent amendments. The reproduction, distribution and use of this e-mail in the absence of the recipient's authorization is forbidden. If you receive this e-mail by mistake, please do not disseminate it, inform the sender immediately and delete any copies. The opinions expressed in this message belong to sender alone and may not necessarily reflect those of ANSA AGENCY.

________________________________

**Comment by pstalidis** [comment]
The pilot execution dates have been decided
