### ISSUE TITLE
Daemon for continuous docker-services run and backup security

### ISSUE THREAD

**Issue by tavitto16** [fandangOrg/fandango#72]
We shall have the services running continuously, sometimes the services fall down and not restarted until someone realizes it.

**Comment by pstalidis** [comment]
The first step should be to add a cronjob to start all services at boot time.

**Comment by danielevannella** [comment]
why did you assign this to me?

Il giorno ven 25 ott 2019 alle ore 14:41 Panagiotis Stalidis <
notifications@github.com> ha scritto:

**Comment by pstalidis** [comment]
I have created start scripts for all of certh's services, called "start.sh". They start docker in interactive mode so that we can monitor the output. You can also use docker-container.yml files in the same folders.

For the 3 crawling services they are in /data/services/crawlers/.
The offline media and topics/ner services are in /data/services/user_interface/.
For the online service it is in /data/services/user_interface/Online/. This is the only service needed for the UI to work.

@federicovagnoni can you add some script for continuous running?
@danielevannella because you probably need to know the status of this issue and because you might need to take some actions for your services

**Comment by tavitto16** [comment]
According to our conversation (14/11/19),  the services are now up and running continuously. So this issue can be closed
