### ISSUE TITLE
Fix for authors that represent groups

### ISSUE THREAD

**Issue by pstalidis** [fandangOrg/fandango#91]
The end-users have noted that there are cases where author.name might represent a group of authors, for example we might find "Newsroom" as the author name.

The major problem that arises is if there is a "Newsroom" author in multiple sources, we have to make a distinction between them.

In order to solve this, the end-users will mark a list of author names as single authors or group authors (i.e "Newsroom")

Then, the list of author names that belong to this list should be treated differently in the Author analysis module, by appending (or pre-pending) the source (domain name)

**Comment by pstalidis** [comment]
Breaking it down to specific actions, @neilpbyrne can you provide a list of all the unique author.names that appear in the ingested articles so that we can give it to the end-users?

**Comment by dmgutierrez** [comment]
So, in order to generate the **unique identifier** of the author, I'm using the **name as well as the source domain**. Thus, let's consider that we receive 2 articles:

- **Article A** has an author named as **PersonA** and it was published by **OrgA**
- **Article B** has an author named as **PersonA** and it was published by **OrgB**

Since the identifier is based on both the name and the source domain, two different entries will be created in Elasticsearch. One of them will be associated to **OrgA** and the other to **OrgB**.

Consequently, we are assuming of course that the authors are different since we only have a name as input.

**Comment by pstalidis** [comment]
Apparently different "groups" are already distinguished, therefore no action is needed.
